In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
data1 = [10, 9.9, 10, 9.8,9.9]

In [4]:
arr1 = np.array(data1)

In [5]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [6]:
arr1

array([10. ,  9.9, 10. ,  9.8,  9.9])

In [7]:
# shape 각차원의 갯수
# (2,) 1차원 2개
# (2, 3, 7) 1차원2개, 2차원 3개, 3차원은 7개

shape_test = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
shape_test.shape # (2, 3) 1차원2개, 2차원 3개

(2, 3)

In [8]:
type(arr1) # 넘파이 배열타입은 배열연산에 특화된 배열타입이다.

numpy.ndarray

In [9]:
arr1.shape #(5,) 1차원배열이고 1차원의 사이즈는 5

(5,)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
np.zeros((3,5)) # 0으로 이루어진 3차원배열이고 각 배열의 사이즈는 5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros(5) # 0으로 이루어진 1차원배열이고 사이즈는 5

array([0., 0., 0., 0., 0.])

In [13]:
np.ones((2,7)) # 1로 이루어진 2차원 배열이고 각 배열의 사이즈는 7

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
data2 = [ [1,2,3,4], [5,6,7,8] ] 

In [16]:
type(data2)

list

In [17]:
arr2 = np.array(data2)

In [18]:
type(arr2)

numpy.ndarray

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int64')

In [23]:
np.arange(10) # 0부터 9까지 1씩 증가하는 NumPy 배열 생

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr = np.array([1,2,3,4,5], dtype=np.int64)
arr

array([1, 2, 3, 4, 5])

In [25]:
arr.dtype

dtype('int64')

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr

array([1., 2., 3., 4., 5.])

In [28]:
float_arr.dtype

dtype('float64')

In [29]:
arr1

array([10. ,  9.9, 10. ,  9.8,  9.9])

In [30]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
arr1 = np.array( [[1,2,3],[4,5,6]],  dtype=np.float64)

In [32]:
arr2 = np.array( [[7,8,9],[10,11,12]],  dtype=np.float64)

In [33]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [35]:
# ndarray는 벡터 연산(element-wise 연산) 을 수행합니다
arr1 + arr2 # numpy배열 방식의 연산(list의 연산과는 다르다)

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [36]:
# 리스트의 연산 예
list1 = [1, 2, 3]
list2 = [4, 5, 6]

print(list1 * 2)    
# print(list1 + 2) # error
print(list1 + list2)   # 리스트 연결(concatenation)

[1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6]


In [37]:
arr1 * arr2 # numpy배열 방식의 연산(list의 연산과는 다르다)

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [38]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [39]:
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
names = np.array(['pyo','sunyoung','psy','pyo','sunyoung','sunny','sunyoung'])

In [41]:
data = np.random.randn(7,4) 

In [42]:
names

array(['pyo', 'sunyoung', 'psy', 'pyo', 'sunyoung', 'sunny', 'sunyoung'],
      dtype='<U8')

In [43]:
data

array([[ 1.11980803, -0.12518812,  0.86999462,  0.08241135],
       [ 0.23491419,  0.46936406, -0.65243285,  1.32072683],
       [-0.44118263,  0.27154023,  0.73322901, -1.61955171],
       [-0.70856435, -1.60539826,  0.06699023, -1.72407069],
       [ 0.78186929, -1.4204609 ,  2.36509814,  0.22928337],
       [-0.18667417, -0.3776862 ,  1.79021504,  0.72259092],
       [ 0.50817484, -0.13347764,  0.49445341, -0.32120445]])

In [44]:
data * 10

array([[ 11.19808026,  -1.25188116,   8.69994616,   0.82411353],
       [  2.34914186,   4.69364057,  -6.5243285 ,  13.20726834],
       [ -4.41182628,   2.71540229,   7.33229012, -16.1955171 ],
       [ -7.08564347, -16.05398262,   0.66990232, -17.24070694],
       [  7.81869291, -14.20460896,  23.65098139,   2.29283372],
       [ -1.86674167,  -3.77686201,  17.90215043,   7.2259092 ],
       [  5.08174836,  -1.33477642,   4.94453407,  -3.21204455]])

In [45]:
data * 2

array([[ 2.23961605, -0.25037623,  1.73998923,  0.16482271],
       [ 0.46982837,  0.93872811, -1.3048657 ,  2.64145367],
       [-0.88236526,  0.54308046,  1.46645802, -3.23910342],
       [-1.41712869, -3.21079652,  0.13398046, -3.44814139],
       [ 1.56373858, -2.84092179,  4.73019628,  0.45856674],
       [-0.37334833, -0.7553724 ,  3.58043009,  1.44518184],
       [ 1.01634967, -0.26695528,  0.98890681, -0.64240891]])

In [75]:
data

array([[ 1.11980803, -0.12518812,  0.86999462,  0.08241135],
       [ 0.23491419,  0.46936406, -0.65243285,  1.32072683],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.78186929, -1.4204609 ,  2.36509814,  0.22928337],
       [-0.18667417, -0.3776862 ,  1.79021504,  0.72259092],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [46]:
names == 'sunyoung'

array([False,  True, False, False,  True, False,  True])

In [47]:
data[ 1, : ]

array([ 0.23491419,  0.46936406, -0.65243285,  1.32072683])

In [48]:
data[1:3, 2:4] 

array([[-0.65243285,  1.32072683],
       [ 0.73322901, -1.61955171]])

In [49]:
data[names=='sunyoung', : ]

array([[ 0.23491419,  0.46936406, -0.65243285,  1.32072683],
       [ 0.78186929, -1.4204609 ,  2.36509814,  0.22928337],
       [ 0.50817484, -0.13347764,  0.49445341, -0.32120445]])

In [50]:
data[names=='sunyoung' ]

array([[ 0.23491419,  0.46936406, -0.65243285,  1.32072683],
       [ 0.78186929, -1.4204609 ,  2.36509814,  0.22928337],
       [ 0.50817484, -0.13347764,  0.49445341, -0.32120445]])

In [51]:
data[ (names == 'sunyoung') | (names=='pyo')]

array([[ 1.11980803, -0.12518812,  0.86999462,  0.08241135],
       [ 0.23491419,  0.46936406, -0.65243285,  1.32072683],
       [-0.70856435, -1.60539826,  0.06699023, -1.72407069],
       [ 0.78186929, -1.4204609 ,  2.36509814,  0.22928337],
       [ 0.50817484, -0.13347764,  0.49445341, -0.32120445]])

In [52]:
data[ : , 3]

array([ 0.08241135,  1.32072683, -1.61955171, -1.72407069,  0.22928337,
        0.72259092, -0.32120445])

In [53]:
data

array([[ 1.11980803, -0.12518812,  0.86999462,  0.08241135],
       [ 0.23491419,  0.46936406, -0.65243285,  1.32072683],
       [-0.44118263,  0.27154023,  0.73322901, -1.61955171],
       [-0.70856435, -1.60539826,  0.06699023, -1.72407069],
       [ 0.78186929, -1.4204609 ,  2.36509814,  0.22928337],
       [-0.18667417, -0.3776862 ,  1.79021504,  0.72259092],
       [ 0.50817484, -0.13347764,  0.49445341, -0.32120445]])

In [54]:
data[ : , 3 ] < 0

array([False, False,  True,  True, False, False,  True])

In [55]:
data[ data[ : , 3 ]  < 0 , : ]

array([[-0.44118263,  0.27154023,  0.73322901, -1.61955171],
       [-0.70856435, -1.60539826,  0.06699023, -1.72407069],
       [ 0.50817484, -0.13347764,  0.49445341, -0.32120445]])

In [56]:
data[ data[ : , 3 ]  < 0 , : ] = 0

In [57]:
data

array([[ 1.11980803, -0.12518812,  0.86999462,  0.08241135],
       [ 0.23491419,  0.46936406, -0.65243285,  1.32072683],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.78186929, -1.4204609 ,  2.36509814,  0.22928337],
       [-0.18667417, -0.3776862 ,  1.79021504,  0.72259092],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [58]:
a = [1,2,3]
b = [1,2,3]

In [59]:
type(a)

list

In [60]:
print(a+b)

[1, 2, 3, 1, 2, 3]


In [61]:
c = np.array([1,2,3])
d = np.array([1,2,3])

In [62]:
type(c)

numpy.ndarray

In [63]:
print(c+d) 

[2 4 6]


In [64]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [65]:
arr * 2 # arr 원본은 변경되지 않는다

array([ 2,  4,  6,  8, 10, 12])

In [66]:
arr

array([1, 2, 3, 4, 5, 6])

In [67]:
c = np.array([1,2,3]) 
d = np.array([1,2,3,4])

In [68]:
#print(c+d)
#ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [69]:
# 수학의 행렬의 곱연산
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# 수학의 행렬의 곱연산 
# 1×5 + 2×7) = 19
# (1×6 + 2×8) = 22
# (3×5 + 4×7) = 43
# (3×6 + 4×8) = 50

print(np.dot(A, B)) # or print(A @ B) 같은 연산

[[19 22]
 [43 50]]


In [70]:
# NumPy에서는 수학의 행렬 곱을 그대로 @ 또는 dot으로 계산할 수 있다.
print(A @ B)

[[19 22]
 [43 50]]


In [71]:
# 데이터 분석에서 행렬과 백터의 곱이 필요한 이유
import numpy as np

X = np.array([
 [2, 80],
 [3, 70],
 [1, 90],
 [4, 60],
 [5, 85],
 [2, 75],
 [3, 95],
 [6, 50],
 [4, 88],
 [5, 92]
])

w = np.array([0.5, 0.01])

y = X @ w

print(y) # 이건 10명의 사람 각각에 대한 결과값입니다.

[1.8  2.2  1.4  2.6  3.35 1.75 2.45 3.5  2.88 3.42]


In [72]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

In [73]:
# 행렬 내적
np.dot(a, b)
# 또는
a @ b

np.int64(11)

In [74]:
# 행렬 외적
np.outer(a, b)

array([[3, 4],
       [6, 8]])