In [1]:
import numpy as np

In [2]:
data1 = [10, 9.9, 10, 9.8,9.9]

In [3]:
arr1 = np.array(data1)

In [4]:
#np.array?

In [5]:
arr1

array([10. ,  9.9, 10. ,  9.8,  9.9])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [8]:
arr1.dtype

dtype('float64')

In [9]:
np.zeros((3,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
data2 = [ [1,2,3,4], [5,6,7,8] ] 

In [14]:
type(data2)

list

In [15]:
arr2 = np.array(data2)

In [16]:
type(arr2)

numpy.ndarray

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int64')

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr = np.array([1,2,3,4,5], dtype=np.int64)
arr

array([1, 2, 3, 4, 5])

In [23]:
arr.dtype

dtype('int64')

In [24]:
float_arr = arr.astype(np.float64)

In [25]:
float_arr

array([1., 2., 3., 4., 5.])

In [26]:
float_arr.dtype

dtype('float64')

In [27]:
arr1

array([10. ,  9.9, 10. ,  9.8,  9.9])

In [28]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr1 = np.array( [[1,2,3],[4,5,6]],  dtype=np.float64)

In [30]:
arr2 = np.array( [[7,8,9],[10,11,12]],  dtype=np.float64)

In [31]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [33]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [34]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [35]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [36]:
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [37]:
names = np.array(['pyo','sunyoung','psy','pyo','sunyoung','sunny','sunyoung'])

In [38]:
data = np.random.randn(7,4) 

In [39]:
names

array(['pyo', 'sunyoung', 'psy', 'pyo', 'sunyoung', 'sunny', 'sunyoung'],
      dtype='<U8')

In [63]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.18755742,  0.72935516, -0.16272245,  0.79047698],
       [-0.27195775,  1.26461555,  0.88786483,  0.55603969],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.2776416 ,  0.83177799,  1.22325381,  0.84959585],
       [ 0.44282804,  0.27229739,  2.35329591,  0.44409428],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [64]:
data * 10

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.87557419,  7.2935516 , -1.62722446,  7.90476976],
       [-2.7195775 , 12.64615548,  8.87864834,  5.56039691],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-2.77641603,  8.31777992, 12.2325381 ,  8.49595852],
       [ 4.42828038,  2.72297386, 23.5329591 ,  4.44094283],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [65]:
data * 2

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.37511484,  1.45871032, -0.32544489,  1.58095395],
       [-0.5439155 ,  2.5292311 ,  1.77572967,  1.11207938],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.55528321,  1.66355598,  2.44650762,  1.6991917 ],
       [ 0.88565608,  0.54459477,  4.70659182,  0.88818857],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [41]:
names == 'sunyoung'

array([False,  True, False, False,  True, False,  True])

In [42]:
data[ 1, : ]

array([-0.18755742,  0.72935516, -0.16272245,  0.79047698])

In [43]:
data[1:3, 2:4] 

array([[-0.16272245,  0.79047698],
       [ 0.88786483,  0.55603969]])

In [44]:
data[names=='sunyoung', : ]

array([[-0.18755742,  0.72935516, -0.16272245,  0.79047698],
       [-0.2776416 ,  0.83177799,  1.22325381,  0.84959585],
       [ 1.585103  , -0.73093972,  0.89548299, -0.38855078]])

In [45]:
data[names=='sunyoung' ]

array([[-0.18755742,  0.72935516, -0.16272245,  0.79047698],
       [-0.2776416 ,  0.83177799,  1.22325381,  0.84959585],
       [ 1.585103  , -0.73093972,  0.89548299, -0.38855078]])

In [46]:
data[ (names == 'sunyoung') | (names=='pyo')]

array([[-0.92631807, -0.58328829,  0.2480183 , -0.31478918],
       [-0.18755742,  0.72935516, -0.16272245,  0.79047698],
       [-0.59024119, -0.08501667,  0.913752  , -0.26075262],
       [-0.2776416 ,  0.83177799,  1.22325381,  0.84959585],
       [ 1.585103  , -0.73093972,  0.89548299, -0.38855078]])

In [47]:
data[ : , 3]

array([-0.31478918,  0.79047698,  0.55603969, -0.26075262,  0.84959585,
        0.44409428, -0.38855078])

In [48]:
data

array([[-0.92631807, -0.58328829,  0.2480183 , -0.31478918],
       [-0.18755742,  0.72935516, -0.16272245,  0.79047698],
       [-0.27195775,  1.26461555,  0.88786483,  0.55603969],
       [-0.59024119, -0.08501667,  0.913752  , -0.26075262],
       [-0.2776416 ,  0.83177799,  1.22325381,  0.84959585],
       [ 0.44282804,  0.27229739,  2.35329591,  0.44409428],
       [ 1.585103  , -0.73093972,  0.89548299, -0.38855078]])

In [49]:
data[ : , 3 ] < 0

array([ True, False, False,  True, False, False,  True])

In [50]:
data[ data[ : , 3 ]  < 0 , : ]

array([[-0.92631807, -0.58328829,  0.2480183 , -0.31478918],
       [-0.59024119, -0.08501667,  0.913752  , -0.26075262],
       [ 1.585103  , -0.73093972,  0.89548299, -0.38855078]])

In [51]:
data[ data[ : , 3 ]  < 0 , : ] = 0

In [52]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.18755742,  0.72935516, -0.16272245,  0.79047698],
       [-0.27195775,  1.26461555,  0.88786483,  0.55603969],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.2776416 ,  0.83177799,  1.22325381,  0.84959585],
       [ 0.44282804,  0.27229739,  2.35329591,  0.44409428],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [53]:
a = [1,2,3]
b = [1,2,3]

In [54]:
type(a)

list

In [55]:
print(a+b)

[1, 2, 3, 1, 2, 3]


In [56]:
c = np.array([1,2,3])
d = np.array([1,2,3])

In [57]:
type(c)

numpy.ndarray

In [58]:
print(c+d) 

[2 4 6]


In [59]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [60]:
arr * 2

array([ 2,  4,  6,  8, 10, 12])

In [61]:
c = np.array([1,2,3]) 
d = np.array([1,2,3,4])

In [62]:
#print(c+d)
#ValueError: operands could not be broadcast together with shapes (3,) (4,) 