In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#np.sqrt?

In [4]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
x = np.random.rand(10)
x

array([0.58528084, 0.42756482, 0.87383925, 0.44150766, 0.02992714,
       0.39211753, 0.29218604, 0.05764435, 0.46548236, 0.82392272])

In [6]:
y = np.random.rand(10)

In [7]:
y

array([0.00434857, 0.68277143, 0.6915249 , 0.68860939, 0.61612175,
       0.08609478, 0.99687182, 0.98802317, 0.37382909, 0.62153041])

In [8]:
np.maximum(x,y)

array([0.58528084, 0.68277143, 0.87383925, 0.68860939, 0.61612175,
       0.39211753, 0.99687182, 0.98802317, 0.46548236, 0.82392272])

In [9]:
arr2 = np.random.randn(6,5)
arr2

array([[ 0.39255169,  1.01649851,  0.61732265, -0.60306659,  0.33243857],
       [ 0.17846256,  0.24030805, -0.36885817,  0.84468591,  0.33495152],
       [-0.70581304,  1.02294593,  2.31269189,  1.48918235,  1.35356617],
       [ 0.72055359, -0.05000467, -1.26145367, -0.70359725,  1.73714753],
       [-1.16974   , -0.5268164 ,  0.79078286,  1.07781179,  1.02808333],
       [ 1.43106395, -1.88310408, -1.03465224, -1.26811369, -0.36265769]])

In [10]:
arr2.sum()

np.float64(6.983171370088762)

In [11]:
arr2.mean()

np.float64(0.23277237900295872)

In [12]:
arr2.sum(axis=0) 

array([ 0.84707875, -0.18017264,  1.05583331,  0.83690251,  4.42352944])

In [13]:
arr2.sum(axis=1) 

array([ 1.75574483,  1.22954987,  5.4725733 ,  0.44264554,  1.20012158,
       -3.11746375])

In [14]:
arr2 > 0

array([[ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [ True, False, False, False,  True],
       [False, False,  True,  True,  True],
       [ True, False, False, False, False]])

In [15]:
(arr2 > 0).sum() 

np.int64(18)

In [16]:
print(np.__version__)

2.3.5


In [17]:
!pip show numpy

Name: numpy
Version: 2.3.5
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2025, NumPy Developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are
 met:

     * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above
        copyright notice, this list of conditions and the following
        disclaimer in the documentation and/or other materials provided
        with the distribution.

     * Neither the name of the NumPy Developers nor the names of any
        contributors may be used to endorse or promote products derived
        from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED

In [18]:
arr4 = np.random.randn(5,3)
arr4

array([[ 0.14854538, -0.10284003, -0.56274002],
       [ 1.94690278, -0.42972855,  0.37312666],
       [-0.97859435,  0.47530551,  1.29556512],
       [ 0.3771601 ,  0.64419237, -1.94578216],
       [-1.10543897,  0.01413352, -0.80793274]])

In [19]:
np.sort(arr4, axis=0)

array([[-1.10543897, -0.42972855, -1.94578216],
       [-0.97859435, -0.10284003, -0.80793274],
       [ 0.14854538,  0.01413352, -0.56274002],
       [ 0.3771601 ,  0.47530551,  0.37312666],
       [ 1.94690278,  0.64419237,  1.29556512]])

In [20]:
np.sort(arr4, axis=1)

array([[-0.56274002, -0.10284003,  0.14854538],
       [-0.42972855,  0.37312666,  1.94690278],
       [-0.97859435,  0.47530551,  1.29556512],
       [-1.94578216,  0.3771601 ,  0.64419237],
       [-1.10543897, -0.80793274,  0.01413352]])

In [21]:
arr4.sort(axis=0)

In [22]:
arr4

array([[-1.10543897, -0.42972855, -1.94578216],
       [-0.97859435, -0.10284003, -0.80793274],
       [ 0.14854538,  0.01413352, -0.56274002],
       [ 0.3771601 ,  0.47530551,  0.37312666],
       [ 1.94690278,  0.64419237,  1.29556512]])

In [23]:
names = np.array(['pyo','sunyoung','psy','pyo','sunyoung','sunny','sunyoung'])

In [24]:
np.unique(names) 

array(['psy', 'pyo', 'sunny', 'sunyoung'], dtype='<U8')

In [25]:
arr2.sum()

np.float64(6.983171370088762)

In [26]:
arr2.sum()

np.float64(6.983171370088762)