In [1]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0:2, 0:2] # 0행부터 1행까지 0열부터 1열까지

array([[1, 2],
       [4, 5]])

In [ ]:
arr[1, :] # 1행전체

array([4, 5, 6])

In [ ]:
arr[:, 2] # 모든 행의 2열(3번째열:인덱스는 0부터)

array([3, 6, 9])